### PR TITLE
Try argopy with PythonCall and CondaPkg instead

### PR DESCRIPTION
**Pull request by gaelforget**
The use of [PythonCall.jl](https://github.com/JuliaPy/PythonCall.jl#readme) and [CondaPkg.jl](https://github.com/JuliaPy/CondaPkg.jl#readme) instead of `PyCall.jl` and `Conda.jl` should provide a more consistent handling of conda/python dependencies of `argooy` (e.g. restricting `xarray` versions`).

This works partly. See https://github.com/euroargodev/ArgoData.jl/actions/runs/11022333147/job/30611391365

The first command `ds_fetcher=argopy.DataFetcher().float(pylist([6902746, 6902747, 6902757, 6902766]))` returns 

```
Python:
<datafetcher.erddap>
Name: Ifremer erddap Argo data fetcher for floats
API: https://erddap.ifremer.fr/erddap
Domain: WMO6902746;WMO6902747;WMO6902757;WMO6902766
Performances: cache=False, parallel=False
User mode: standard
Dataset: phy
```

But the `ds_points = ds_fetcher.to_xarray()` command gives the following error. 

```
ERROR: Python: ClientConnectorCertificateError: Cannot connect to host erddap.ifremer.fr:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')]
Python stacktrace:
 [1] _wrap_create_connection
   @ aiohttp.connector ~/.julia/environments/v1.10/.CondaPkg/env/lib/python3.11/site-packages/aiohttp/connector.py:1082
 [2] _create_direct_connection
   @ aiohttp.connector ~/.julia/environments/v1.10/.CondaPkg/env/lib/python3.11/site-packages/aiohttp/connector.py:1319
```

with 

```
julia> CondaPkg.status()
Packages
  argopy v0.1.16 (0.1.16)
  xarray v2024.2.0 (>=0.18,<2024.3)
```

@gmaze , any idea what I may be doing wrong?

### CODE REVIEW

**Comment by gmaze** [comment]
Hi @gaelforget 
We should first determine if this is an error due to the erddap server or to argopy or something elese
Do you have the error when using the `src='argovis'` or `src='gdac'` for instance ?

Note that the erddap server had some down time yesterday, so you may simply have hit the server at the wrong time ...

**Comment by gaelforget** [comment]
Thanks! It's server issue it appears, which affects the three data sources, leading to different error messages :

```
julia> argopy.status()
Python: src argovis is: offline | src erddap is: offline | src gdac is: offline
```

```
ERROR: Python: FtpPathError: This path is not GDAC compliant (no `dac` folder with legitimate sub-folder):
https://data-argo.ifremer.fr
Python stacktrace:
 [1] check_gdac_path
   @ argopy.options ~/.julia/environments/v1.10/.CondaPkg/env/lib/python3.11/site-packages/argopy/options.py:269
```

```
julia> ds_points = ds_fetcher.to_xarray()
ERROR: Python: DataNotFound: "['https://argovis-api.colorado.edu/argo?platform=6902746&data=pressure,temperature,salinity', 'https://argovis-api.colorado.edu/argo?platform=6902747&data=pressure,temperature,salinity', 'https://argovis-api.colorado.edu/argo?platform=6902757&data=pressure,temperature,salinity', 'https://argovis-api.colorado.edu/argo?platform=6902766&data=pressure,temperature,salinity']"
Python stacktrace:
 [1] open_mfjson
   @ argopy.stores.filesystems ~/.julia/environments/v1.10/.CondaPkg/env/lib/python3.11/site-packages/argopy/stores/filesystems.py:1422
```

and 

```
julia> ds_fetcher=argopy.DataFetcher().float(pylist([6902746, 6902747, 6902757, 6902766]),src="gdap")
ERROR: Python: TypeError: checkAccessPoint.<locals>.wrapper() got an unexpected keyword argument 'src'
Python stacktrace: none
Stacktrace:
 [1] pythrow()
   @ PythonCall.Core ~/.julia/packages/PythonCall/Nr75f/src/Core/err.jl:92
```

**Comment by gaelforget** [comment]
Any idea why `argopy.status()` reports that all servers are offline?

**Comment by gaelforget** [comment]
> Any idea why `argopy.status()` reports that all servers are offline?

As a test, I tried directly in python and had no issues. 

```
>>> argopy.status()
src argovis is: ok | src erddap is: ok | src gdac is: ok
>>> from argopy import DataFetcher as ArgoDataFetcher
>>> ds = ArgoDataFetcher().region([-75, -45, 20, 30, 0, 100, '2011-01', '2011-06']).to_xarray()
```

So it seems that something is getting lost in translation when we try to do this via `PythonCall.jl`

Not sure what to try next though ...

**Comment by gaelforget** [comment]
One more test 

```
julia> list_src=argopy.utils.list_available_data_src()
julia> list_src["erddap"].api_server_check
Python: 'https://erddap.ifremer.fr/erddap/info/ArgoFloats/index.json'
julia> argopy.utils.isalive(list_src["erddap"].api_server_check)
Python: False
julia> argopy.utils.isconnected(list_src["erddap"].api_server_check)
Python: False
```

**Comment by gmaze** [comment]
Looks like this is a Julia issue, not dealing as expected with the urllib python features

**Comment by gaelforget** [comment]
> Looks like this is a Julia issue, not dealing as expected with the urllib python features

I think this was it. The following works : 

```
using PythonCall
@py import ssl
p=ssl.get_default_verify_paths()
cafile=string(p.cafile)
ENV["SSL_CERT_FILE"] = cafile

using ArgoData
argopy=ArgoData.pyimport("argopy")
```

now gives : 

```
julia> argopy.status()
Python: src argovis is: ok | src erddap is: ok | src gdac is: ok
```

and : 

```
julia> ds_points = ds_fetcher.to_xarray()
Python:
<xarray.Dataset> Size: 30MB
Dimensions:          (N_POINTS: 248145)
Coordinates:
  * N_POINTS         (N_POINTS) int64 2MB 0 1 2 3 ... 248142 248143 248144
    LATITUDE         (N_POINTS) float64 2MB 20.33 20.33 20.33 ... 23.2 23.2 23.2
    LONGITUDE        (N_POINTS) float64 2MB -49.45 -49.45 ... -55.21 -55.21
    TIME             (N_POINTS) datetime64[ns] 2MB 2017-03-28T11:55:00 ... 20...
Data variables: (12/15)
    CYCLE_NUMBER     (N_POINTS) int64 2MB 1 1 1 1 1 1 ... 247 247 247 247 247
    DATA_MODE        (N_POINTS) <U1 993kB 'D' 'D' 'D' 'D' ... 'D' 'D' 'D' 'D'
    DIRECTION        (N_POINTS) <U1 993kB 'D' 'D' 'D' 'D' ... 'A' 'A' 'A' 'A'
    PLATFORM_NUMBER  (N_POINTS) int64 2MB 6902766 6902766 ... 6902766 6902766
    POSITION_QC      (N_POINTS) int64 2MB 1 1 1 1 1 1 1 1 1 ... 1 1 1 1 1 1 1 1
    PRES             (N_POINTS) float32 993kB 12.2 17.0 ... 2.013e+03 2.018e+03
    ...               ...
    PSAL_ERROR       (N_POINTS) float32 993kB 0.01 0.01 0.01 ... 0.01 0.01 0.01
    PSAL_QC          (N_POINTS) int64 2MB 1 1 1 1 1 1 1 1 1 ... 1 1 1 1 1 1 1 1
    TEMP             (N_POINTS) float32 993kB 24.38 24.38 24.38 ... 3.716 3.709
    TEMP_ERROR       (N_POINTS) float32 993kB 0.002 0.002 0.002 ... 0.002 0.002
    TEMP_QC          (N_POINTS) int64 2MB 1 1 1 1 1 1 1 1 1 ... 1 1 1 1 1 1 1 1
    TIME_QC          (N_POINTS) int64 2MB 1 1 1 1 1 1 1 1 1 ... 1 1 1 1 1 1 1 1
Attributes:
    DATA_ID:              ARGO
    DOI:                  http://doi.org/10.17882/42182
    Fetched_from:         https://erddap.ifremer.fr/erddap
    Fetched_by:           gforget
    Fetched_date:         2024/09/25
    Fetched_constraints:  WMO6902746;WMO6902747;WMO6902757;WMO6902766
    Fetched_uri:          ['https://erddap.ifremer.fr/erddap/tabledap/ArgoFlo...
    history:              Variables filtered according to DATA_MODE; Variable...
```

**Comment by gmaze** [comment]
awesome !

**Comment by gaelforget** [comment]
> awesome !

Thanks for your help on this. Makes me really happy that this integration with `argopy` looks to be back on track. 

I will merge the PR now, and check on the docs updates [in the docs here](https://euroargodev.github.io/ArgoData.jl/dev/examples/#Argo-via-Python-API) once built. Next steps would be :  release `0.1.23`, and update the Pluto notebook.

**Pull request merged**
